#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.join(__dir__, '../lib')
require 'railroad_diagrams'
require 'railroad_diagrams/cli/command'

exit RailroadDiagrams::CLI::Command.new.run(ARGV.dup)
