name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.5
  test:
    needs: ruby-versions
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          exe/railroad_diagrams --format=svg
          exe/railroad_diagrams --format=ascii
          exe/railroad_diagrams --format=unicode
          exe/railroad_diagrams --format=standalone
